services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jose\Component\Encryption\Algorithm\ContentEncryption\A128CBCHS256:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128CBC-HS256'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A192CBCHS384:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A192CBC-HS384'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A256CBCHS512:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256CBC-HS512'}

    Jose\Component\Encryption\Algorithm\ContentEncryption\A128GCM:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128GCM'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A192GCM:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A192GCM'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A256GCM:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256GCM'}

    Jose\Component\Encryption\Algorithm\KeyEncryption\A128GCMKW:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128GCMKW'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\A192GCMKW:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A192GCMKW'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\A256GCMKW:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256GCMKW'}

    Jose\Component\Encryption\Algorithm\KeyEncryption\Dir:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'dir'}

    Jose\Component\Encryption\Algorithm\KeyEncryption\ECDHES:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'ECDH-ES'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\ECDHESA128KW:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'ECDH-ES+A128KW'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\ECDHESA192KW:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'ECDH-ES+A192KW'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\ECDHESA256KW:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'ECDH-ES+A256KW'}

    Jose\Component\Encryption\Algorithm\KeyEncryption\A128KW:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128KW'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\A192KW:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A192KW'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\A256KW:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256KW'}

    Jose\Component\Encryption\Algorithm\KeyEncryption\PBES2HS256A128KW:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'PBES2-HS256+A128KW'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\PBES2HS384A192KW:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'PBES2-HS384+A192KW'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\PBES2HS512A256KW:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'PBES2-HS512+A256KW'}

    Jose\Component\Encryption\Algorithm\KeyEncryption\RSA15:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'RSA1_5'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\RSAOAEP:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'RSA-OAEP'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\RSAOAEP256:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'RSA-OAEP-256'}

# ---- New algorithms ----
# These algorithms are out of the main specifications but referenced in
# some WebAuthn documents.
#
# They may be subject to changes.
# ------------------------

    Jose\Component\Encryption\Algorithm\KeyEncryption\Chacha20Poly1305:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'chacha20-poly1305'}

    Jose\Component\Encryption\Algorithm\KeyEncryption\A128CTR:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128CTR'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\A256CTR:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256CTR'}

    Jose\Component\Encryption\Algorithm\KeyEncryption\RSAOAEP384:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'RSA-OAEP-384'}

    Jose\Component\Encryption\Algorithm\KeyEncryption\RSAOAEP512:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'RSA-OAEP-512'}


    Jose\Component\Encryption\Algorithm\ContentEncryption\A128CCM_16_64:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128CCM-16-64'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A128CCM_16_128:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128CCM-16-128'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A128CCM_64_64:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128CCM-64-64'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A128CCM_64_128:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128CCM-64-128'}

    Jose\Component\Encryption\Algorithm\ContentEncryption\A256CCM_16_64:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256CCM-16-64'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A256CCM_16_128:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256CCM-16-256'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A256CCM_64_64:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256CCM-64-64'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A256CCM_64_128:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256CCM-64-256'}
