services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jose\Component\Signature\Algorithm\ES256:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'ES256'}
    Jose\Component\Signature\Algorithm\ES384:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'ES384'}
    Jose\Component\Signature\Algorithm\ES512:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'ES512'}

    Jose\Component\Signature\Algorithm\RS256:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'RS256'}
    Jose\Component\Signature\Algorithm\RS384:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'RS384'}
    Jose\Component\Signature\Algorithm\RS512:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'RS512'}

    Jose\Component\Signature\Algorithm\PS256:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'PS256'}
    Jose\Component\Signature\Algorithm\PS384:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'PS384'}
    Jose\Component\Signature\Algorithm\PS512:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'PS512'}

    Jose\Component\Signature\Algorithm\HS256:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'HS256'}
    Jose\Component\Signature\Algorithm\HS384:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'HS384'}
    Jose\Component\Signature\Algorithm\HS512:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'HS512'}

    Jose\Component\Signature\Algorithm\EdDSA:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'EdDSA'}

    Jose\Component\Signature\Algorithm\None:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'none'}
