services:
    jose.jwk_source.keyfile:
        public: false
        class: 'Jose\Bundle\KeyManagement\DependencyInjection\Source\JWKSource\KeyFile'
        tags:
            - {'name': 'jose.jwk_source' }
    jose.jwk_source.certificatefile:
        public: false
        class: 'Jose\Bundle\KeyManagement\DependencyInjection\Source\JWKSource\CertificateFile'
        tags:
            - {'name': 'jose.jwk_source'}
    jose.jwk_source.values:
        public: false
        class: 'Jose\Bundle\KeyManagement\DependencyInjection\Source\JWKSource\Values'
        tags:
            - {'name': 'jose.jwk_source'}
    jose.jwk_source.jwk:
        public: false
        class: 'Jose\Bundle\KeyManagement\DependencyInjection\Source\JWKSource\JWK'
        tags:
            - {'name': 'jose.jwk_source'}
    jose.jwk_source.x5c:
        public: false
        class: 'Jose\Bundle\KeyManagement\DependencyInjection\Source\JWKSource\X5C'
        tags:
            - {'name': 'jose.jwk_source'}
    jose.jwk_source.jwkset:
        public: false
        class: 'Jose\Bundle\KeyManagement\DependencyInjection\Source\JWKSource\JWKSet'
        tags:
            - {'name': 'jose.jwk_source'}
